export default {
  SPLASH: 'splash',
  BOTTOM_TABS: 'bottomTabs',
  FRIENDS_STACK: 'friendStack',
  INSPIRATION_STACK: 'inspirationStack',
  ADVENTURE_STACK: 'adventureStack',
  HELP_STACK: 'helpStack',
  GUIDES_STACK: 'guidesStack',
  AUTH_OPTION: 'authOption',
  INTRO_SCREEN: 'introScreen',
  CREATE_PROFILE_USER: 'createProfileUser',
  CREATE_PROFILE_GUIDE: 'createProfileGuide',
  UNDER_REVIEW: 'underReview',
  RESET_PASSWORD: 'resetPassword',
  LOGIN: 'login',
  SIGNUP: 'signUp',
  FORGOT_PASSWORD: 'forgotPassword',
  OTP_VERIFY: 'otpVerify',
  HOME: 'Home',
  PROFILE: 'profile',
  CMS: 'cms',
  CHANGE_PASSWORD: 'changePassword',
  DELETE_ACCOUNT: 'deleteAccount',
  CHATS: 'chats',
  FRIENDS: 'friends',
  INSPIRATION: 'inspiration',
  ADVENTURE: 'adventure',
  HELP: 'help',
  GUIDES: 'guides',
  SETTINGS: 'settings',
  FEED_USER_PROFILE: 'feedUserProfile',
  CREATE_GROUP: 'createGroup',
  PROFILE_DETAILS: 'profileDetails',
  CREATE_PROFILE_USER_TOKEN: 'createProfileUserToken',
  CREATE_PROFILE_GUIDE_TOKEN: 'createProfileGuideToken',
  EDIT_PROFILE: 'editProfile',
  CATEGORIES: 'categories',
  SEARCH_SCREEN: 'searchScreen',
  PROCEDURE: 'procedure',
  REPOSITORIES: 'repositories',
  DIRECTORIES: 'Directories',
  CASE_DETAILS: 'caseDetails',
  ACCESS_REQUEST: 'accessRequest',
  OTP_VERIFY_TOKEN: 'otpVerifyToken',
  ATTORNEY: 'attorney',
  MEDIATOR: 'mediator',
  NOTICE_PANEL: 'noticePanel',
  MY_ADVERTISEMENT: 'myAdvertisement',
  MY_DOWNLOADS: 'myDownloads',
  EXPORT: 'export',
  NOTIFICATION: 'notification',
  EDIT_SCREEN: 'editScreen',
  SCAN_DOCS: 'scanDocs',
  CUSTOMER_SUPPORT: 'customerSupport',
  FAQS: 'faqs',
  SUBSCRIPTION_PLANS: 'subscriptionPlans',
  SCAN_DOCS_SCREEN: 'scanDocsScreen',
  EDIT_DETAILS: 'editDetails',
  BUSINESS_CARD_DETAILS: 'businessCardDetails',
  INVITE_FRIEND:'inviteFriend',
  YOUR_CONNECTIONS:'yourConnections',
  QR_CODE:'qrCode',
  CONNECTION_DETAILS:'connectionDetails',
  INTERNAL_SHARING:'internalSharing',
  SHARED_CONTACTS:'sharedContacts',
  AMBASSADOR_CELEBRATION: 'ambassadorCelebration',

   };
